/* generated by pull.js */
const manifest = {
  "name": "Opacity slider",
  "description": "Adds an opacity slider to the costume editor color picker.",
  "tags": [
    "beta",
    "new"
  ],
  "info": [
    {
      "type": "info",
      "text": "The opacity slider is disabled when no object is selected, or when in bitmap mode.",
      "id": "bitmapModeincompleteInfo"
    }
  ],
  "credits": [
    {
      "name": "itta611",
      "link": "https://github.com/itta611/"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "enabledByDefault": false
};
export default manifest;
