/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./userstyle.css";
import _asset from "!url-loader!./icons/decrement.svg";
import _asset2 from "!url-loader!./icons/increment.svg";
import _asset3 from "!url-loader!./icons/off.svg";
import _asset4 from "!url-loader!./icons/on.svg";
import _asset5 from "!url-loader!./icons/settings.svg";
import _asset6 from "!url-loader!./icons/snap.svg";
export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css,
  "icons/decrement.svg": _asset,
  "icons/increment.svg": _asset2,
  "icons/off.svg": _asset3,
  "icons/on.svg": _asset4,
  "icons/settings.svg": _asset5,
  "icons/snap.svg": _asset6,
};
