/* generated by pull.js */
const manifest = {
  "name": "Number inputs in color picker",
  "description": "Lets you set an exact value (0-100) for each slider in the costume editor color picker by typing in a number.",
  "credits": [
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber/"
    }
  ],
  "tags": [
    "new"
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ]
};
export default manifest;
