/* generated by pull.js */
const manifest = {
  "name": "Message count on extension icon",
  "description": "Adds the current message count in the Scratch Addons icon.",
  "tags": [
    "recommended",
    "new"
  ],
  "enabledByDefault": false,
  "info": [
    {
      "type": "info",
      "text": "You can use Do Not Disturb (right click extension icon → Do not disturb) to temporarily hide the message count.",
      "id": "dndtohide"
    }
  ],
  "settings": [
    {
      "name": "Badge color",
      "id": "color",
      "type": "color",
      "default": "#008000"
    },
    {
      "name": "Indicate when not signed in",
      "id": "showOffline",
      "type": "boolean",
      "default": false
    }
  ],
  "presets": [
    {
      "name": "Old light green",
      "id": "oldLightGreen",
      "description": "The badge color from the original Scratch Messaging Extension.",
      "values": {
        "color": "#8ce68c"
      }
    },
    {
      "name": "Blue",
      "id": "blue",
      "values": {
        "color": "#175ef8"
      }
    },
    {
      "name": "Black",
      "id": "black",
      "values": {
        "color": "#000000"
      }
    },
    {
      "name": "Orange",
      "id": "orange",
      "description": "The same color as the Scratch Addons logo.",
      "values": {
        "color": "#FF7B26"
      }
    }
  ],
  "credits": [
    {
      "name": "World_Languages"
    },
    {
      "name": "William Horning",
      "link": "https://wgyt.tk/"
    },
    {
      "name": "lisa_wolfgang",
      "link": "https://scratch.mit.edu/users/lisa_wolfgang/"
    }
  ],
  "dynamicDisable": true
};
export default manifest;
