/* generated by pull.js */
const manifest = {
  "name": "Front page curator link",
  "description": "Makes the username of the front page curator a clickable link to their profile.",
  "credits": [
    {
      "name": "Hans5958",
      "link": "https://github.com/Hans5958/userscripts/blob/master/Scratch/Curator%20Links.user.js"
    }
  ],
  "userscripts": [],
  "userstyles": [],
  "settings": [
    {
      "id": "styleAsNormalText",
      "name": "Style as normal text",
      "type": "boolean",
      "default": false
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "relatedAddons": [
    "more-links"
  ],
  "enabledByDefault": false
};
export default manifest;
