/* generated by pull.js */
const manifest = {
  "name": "Quote post number",
  "description": "Click the \"quote post number\" button to include a link to the post in your reply.",
  "userscripts": [],
  "tags": [
    "new"
  ],
  "enabledByDefault": false,
  "dynamicDisable": true,
  "settings": [
    {
      "name": "Automatically add post link to quotes",
      "id": "auto_add",
      "type": "boolean",
      "default": false
    }
  ],
  "credits": [
    {
      "name": "itta611",
      "link": "https://github.com/itta611/"
    }
  ]
};
export default manifest;
