/* generated by pull.js */
const manifest = {
  "name": "Semicolon glitch",
  "description": "Adds the semicolon glitch back to Scratch.",
  "credits": [
    {
      "name": "GrahamSH"
    }
  ],
  "userstyles": [],
  "userscripts": [],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
