/* generated by pull.js */
const manifest = {
  "name": "Place backpack code at mouse",
  "description": "Drag-and-drop code blocks to the mouse position instead of to the code area corner.",
  "credits": [
    {
      "name": "Chrome_Cat"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "recommended",
    "new"
  ],
  "dynamicDisable": true,
  "enabledByDefault": true
};
export default manifest;
