/* generated by pull.js */
const manifest = {
  "name": "Studio tools",
  "description": "Lets managers easily promote curators to managers or remove anyone from a studio on the \"curators\" tab, and adds the ability to leave a studio using a button under \"Follow Studio\".",
  "credits": [
    {
      "name": "World_Languages"
    },
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber/"
    }
  ],
  "settings": [
    {
      "name": "Add leave button in studios section of \"My Stuff\"",
      "type": "boolean",
      "default": true,
      "id": "mystufftools"
    }
  ],
  "userscripts": [],
  "userstyles": [],
  "tags": [
    "recommended",
    "new"
  ],
  "dynamicDisable": true,
  "enabledByDefault": true
};
export default manifest;
