/* generated by pull.js */
const manifest = {
  "name": "Old studio layout",
  "description": "Reverts the layout of the studio page back to the one used before the studio update.",
  "tags": [
    "theme"
  ],
  "relatedAddons": [
    "scratch3to2",
    "items-per-row",
    "studio-followers"
  ],
  "credits": [
    {
      "name": "Maximouse",
      "link": "https://scratch.mit.edu/users/Maximouse/"
    }
  ],
  "customCssVariables": [
    {
      "name": "defaultLinkIconFilter",
      "value": {
        "type": "recolorFilter",
        "source": "#855cd6"
      }
    },
    {
      "name": "defaultLinkHoverIconFilter",
      "value": {
        "type": "recolorFilter",
        "source": "#7854c0"
      }
    }
  ],
  "dynamicDisable": true,
  "userscripts": [],
  "userstyles": []
};
export default manifest;
