/* generated by pull.js */
const manifest = {
  "name": "Customizable quotes and code blocks on forums",
  "description": "Shows nicer code and quote blocks on the forums.",
  "credits": [
    {
      "name": "GrahamSH"
    },
    {
      "name": "Boomer001"
    }
  ],
  "settings": [
    {
      "name": "Border Color",
      "id": "bordercolor",
      "type": "color",
      "default": "#855cd6",
      "allowTransparency": true
    }
  ],
  "dynamicDisable": true,
  "userstyles": [],
  "tags": [
    "theme"
  ]
};
export default manifest;
