/* generated by pull.js */
const manifest = {
  "name": "Infinite scrolling",
  "description": "Allow for scrolling on different parts of the site without having to click to \"load more\".",
  "credits": [
    {
      "name": "DatOneLefty"
    },
    {
      "name": "Hans5958"
    }
  ],
  "settings": [
    {
      "name": "Profile Comments",
      "id": "profileCommentScroll",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Project Comments",
      "id": "projectScroll",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Studio Comments",
      "id": "studioScroll",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Studio Projects",
      "id": "studioProjectScroll",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Browse Projects Popup",
      "id": "studioBrowseProjectScroll",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Studio Curators",
      "id": "studioCuratorScroll",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Studio Activity",
      "id": "studioActivityScroll",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Messages",
      "id": "messageScroll",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Search and Explore",
      "id": "searchExploreScroll",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Forums",
      "id": "forumScroll",
      "type": "boolean",
      "default": true
    }
  ],
  "userscripts": [
    {
      "url": "buttonScroll.js"
    }
  ],
  "userstyles": [],
  "tags": [
    "new"
  ],
  "relatedAddons": [
    "full-signature"
  ],
  "enabledByDefault": false
};
export default manifest;
