/* generated by pull.js */
const manifest = {
  "name": "Sound duration display",
  "description": "Adds a display to the sound editor that shows the total length and the elapsed time of the sound, or the selection within it.",
  "credits": [
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber/"
    }
  ],
  "tags": [
    "new"
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "dynamicDisable": true
};
export default manifest;
