/* generated by pull.js */
const manifest = {
  "name": "Hide forum signatures",
  "description": "Hides signatures in forum posts and adds a \"Show signature\" button.",
  "credits": [
    {
      "name": "Weredime (9gr)",
      "link": "https://scratch.mit.edu/users/9gr/"
    }
  ],
  "userscripts": [],
  "settings": [
    {
      "name": "Hide signatures by default",
      "type": "boolean",
      "default": true,
      "id": "hide"
    },
    {
      "name": "Show toggle button",
      "type": "boolean",
      "default": true,
      "id": "toggle"
    }
  ],
  "dynamicDisable": true,
  "enabledByDefault": false,
  "tags": [
    "new"
  ]
};
export default manifest;
