/* generated by pull.js */
const manifest = {
  "name": "Hide project stats",
  "description": "Lets you hide love, favorite, remix, comment, and view counts on project pages, the front page, and My Stuff.",
  "credits": [
    {
      "name": "Weredime (9gr)",
      "link": "https://scratch.mit.edu/users/9gr/"
    },
    {
      "name": "lisa_wolfgang",
      "link": "https://scratch.mit.edu/users/lisa_wolfgang/"
    }
  ],
  "userstyles": [
    {
      "url": "hide_remix_count.css",
      "if": {
        "settings": {
          "remixes": true
        }
      }
    },
    {
      "url": "hide_view_count.css",
      "if": {
        "settings": {
          "views": true
        }
      }
    },
    {
      "url": "hide_love_count.css",
      "if": {
        "settings": {
          "loves": true
        }
      }
    },
    {
      "url": "hide_favorite_count.css",
      "if": {
        "settings": {
          "favorites": true
        }
      }
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "settings": [
    {
      "name": "Hide love count",
      "default": true,
      "id": "loves",
      "type": "boolean"
    },
    {
      "name": "Hide favorite count",
      "default": true,
      "id": "favorites",
      "type": "boolean"
    },
    {
      "name": "Hide remix count",
      "default": true,
      "id": "remixes",
      "type": "boolean"
    },
    {
      "name": "Hide view count",
      "default": true,
      "id": "views",
      "type": "boolean"
    },
    {
      "name": "Hide love count in \"What the Community is Loving\"",
      "default": true,
      "id": "lovesFront",
      "type": "boolean"
    },
    {
      "name": "Hide remix count in \"What the Community is Remixing\"",
      "default": true,
      "id": "remixesFront",
      "type": "boolean"
    },
    {
      "name": "Show stats on my own project pages",
      "default": false,
      "id": "showOwnStats",
      "type": "boolean"
    },
    {
      "name": "Hide stats on My Stuff",
      "default": false,
      "id": "myStuff",
      "type": "boolean"
    },
    {
      "name": "Hide comment count",
      "default": true,
      "id": "comments",
      "type": "boolean",
      "if": {
        "settings": {
          "myStuff": true
        }
      }
    },
    {
      "name": "Hide broken (always 0) studio count",
      "default": true,
      "id": "studios",
      "type": "boolean",
      "if": {
        "settings": {
          "myStuff": true
        }
      }
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
