/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./hide_remix_count.css";
import _css2 from "!css-loader!./hide_view_count.css";
import _css3 from "!css-loader!./hide_love_count.css";
import _css4 from "!css-loader!./hide_favorite_count.css";
export const resources = {
  "userscript.js": _js,
  "hide_remix_count.css": _css,
  "hide_view_count.css": _css2,
  "hide_love_count.css": _css3,
  "hide_favorite_count.css": _css4,
};
