/* generated by pull.js */
const manifest = {
  "name": "YouTube full screen",
  "description": "Enables the full screen button in Scratch's YouTube video player.",
  "credits": [
    {
      "name": "Maximouse",
      "link": "https://scratch.mit.edu/users/Maximouse/"
    }
  ],
  "userscripts": [],
  "dynamicDisable": false,
  "tags": [
    "new"
  ],
  "relatedAddons": [
    "true-youtube-links"
  ],
  "enabledByDefault": false
};
export default manifest;
