/* generated by pull.js */
const manifest = {
  "name": "Delete sprites without confirmation",
  "description": "Removes the confirmation prompt that asks if you are sure you want to delete a sprite.",
  "info": [
    {
      "text": "Tip: If you accidentally delete a sprite, costume, or sound, you can undo the deletion by clicking Edit in the menu bar then Restore.",
      "id": "restoretip"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "hide.css"
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "danger",
    "new"
  ],
  "relatedAddons": [
    "hide-delete-button",
    "confirm-actions"
  ]
};
export default manifest;
