/* generated by pull.js */
const manifest = {
  "name": "Follow topics after posting",
  "description": "Automatically follow forum topics you post on.",
  "tags": [
    "recommended",
    "new"
  ],
  "credits": [
    {
      "name": "Chiroyce",
      "link": "https://github.com/Chiroyce1"
    }
  ],
  "userscripts": [],
  "dynamicDisable": true,
  "enabledByDefault": false
};
export default manifest;
