/* generated by pull.js */
const manifest = {
  "name": "Show user IDs",
  "description": "Adds the user ID next to the username at the top of profile pages.",
  "credits": [
    {
      "name": "yes-i-am-lanky",
      "link": "https://scratch.mit.edu/users/yes-i-am-lanky/"
    },
    {
      "name": "DNin01",
      "link": "https://github.com/DNin01"
    }
  ],
  "userscripts": [],
  "userstyles": [],
  "settings": [
    {
      "id": "only-on-hover",
      "name": "Only show when hovering over username",
      "default": false,
      "type": "boolean"
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
