/* generated by pull.js */
const manifest = {
  "name": "Ctrl+Click to run scripts",
  "description": "Only run scripts on click if also holding the Ctrl key.",
  "info": [
    {
      "text": "On macOS, use the Cmd key instead of the Ctrl key.",
      "id": "macContextDisabled"
    }
  ],
  "credits": [
    {
      "name": "lisa_wolfgang",
      "link": "https://github.com/lisa-wolfgang"
    },
    {
      "name": "apple502j",
      "link": "https://github.com/apple502j"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "new"
  ],
  "relatedAddons": [
    "fix-pasted-scripts"
  ],
  "enabledByDefault": false
};
export default manifest;
