/* generated by pull.js */
const manifest = {
  "name": "My Stuff search",
  "description": "Allows you to search your projects, studios, and trash on the My Stuff page. Simply start typing anywhere on the page to start a search. You can also use Ctrl+Enter after searching to quickly open the top search result.",
  "info": [
    {
      "type": "notice",
      "text": "If you have a lot of projects or studios, the search might take a while.",
      "id": "pleaseBePatient"
    }
  ],
  "tags": [
    "new"
  ],
  "credits": [
    {
      "name": "lisa_wolfgang",
      "link": "https://scratch.mit.edu/users/lisa_wolfgang/"
    }
  ],
  "userstyles": [],
  "userscripts": [],
  "dynamicDisable": true,
  "enabledByDefault": false
};
export default manifest;
