/* generated by pull.js */
const manifest = {
  "name": "Resizable comment input",
  "description": "Makes the comment input box vertically resizable in Scratch 3.0-styled pages.",
  "tags": [
    "recommended",
    "new"
  ],
  "credits": [
    {
      "name": "Maximouse",
      "link": "https://scratch.mit.edu/users/Maximouse/"
    }
  ],
  "dynamicDisable": true,
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "enabledByDefault": true
};
export default manifest;
