/* generated by pull.js */
const manifest = {
  "name": "Message filters",
  "description": "Lets you select filters for types of messages to hide or show on Scratch's messages page.",
  "info": [
    {
      "type": "notice",
      "text": "This does not change your message count. This simply lets you hide certain types of messages on Scratch's messages page.",
      "id": "nomessagecount"
    }
  ],
  "credits": [
    {
      "name": "--Explosion--",
      "link": "https://github.com/explosion-scratch"
    }
  ],
  "userscripts": [],
  "userstyles": [],
  "tags": [
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
