/* generated by pull.js */
const manifest = {
  "name": "Remember collapsed forum categories",
  "description": "Categories you collapsed on the forum home page (the list of forums) will stay collapsed when you leave and come back.",
  "credits": [
    {
      "name": "Steve0Greatness",
      "link": "https://scratch.mit.edu/users/Steve0Greatness/"
    }
  ],
  "userscripts": [],
  "tags": [
    "new"
  ]
};
export default manifest;
