/* generated by pull.js */
const manifest = {
  "name": "Copy link to comment button",
  "description": "Adds a \"Copy Link\" button to all comments on the website, next to the \"Report\" button.",
  "credits": [
    {
      "name": "Sly-Little-Fox",
      "link": "https://github.com/Sly-Little-Fox/"
    }
  ],
  "userscripts": [
    {
      "url": "project.js"
    }
  ],
  "userstyles": [
    {
      "url": "project.css"
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "recommended",
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
