/* generated by pull.js */
const manifest = {
  "name": "Browse followers button in studios",
  "description": "Adds a button at the top of the \"curators\" tab in studios you manage, that lists your followers and followed users and lets you invite a shown user with a single click.",
  "credits": [
    {
      "name": "Weredime (9gr)",
      "link": "https://scratch.mit.edu/users/9gr/"
    },
    {
      "name": "World_Languages"
    }
  ],
  "userscripts": [],
  "userstyles": [],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "relatedAddons": [
    "old-studio-layout"
  ],
  "enabledByDefault": false
};
export default manifest;
