/* generated by pull.js */
const manifest = {
  "name": "Forum post cooldown display",
  "description": "After submitting a forum post, displays a countdown on the submit button showing how long you have to wait before posting again.",
  "tags": [
    "new"
  ],
  "userscripts": [],
  "userstyles": [],
  "credits": [
    {
      "name": "mybearworld",
      "link": "https://scratch.mit.edu/users/mybearworld/"
    }
  ],
  "settings": [
    {
      "name": "Retry after countdown",
      "description": "When posting fails because of the 60 second rule, automatically try again when possible.",
      "type": "boolean",
      "default": false,
      "id": "retry"
    }
  ],
  "dynamicDisable": true
};
export default manifest;
