/* generated by pull.js */
const manifest = {
  "name": "More links",
  "description": "Makes URLs pointing outside scratch.mit.edu clickable.",
  "credits": [
    {
      "name": "Hans5958"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "new"
  ],
  "relatedAddons": [
    "curator-link"
  ],
  "enabledByDefault": false,
  "dynamicDisable": true
};
export default manifest;
