/* generated by pull.js */
const manifest = {
  "name": "Fix sprite pane glitching",
  "description": "Fixes a bug in the Scratch editor where scripts, costumes, and sounds can't be dragged and dropped into sprites without the sprites jumping around within the sprite pane.",
  "credits": [
    {
      "name": "Xan",
      "link": "https://scratch.mit.edu/users/-Xanimation-/"
    },
    {
      "name": "CST1229",
      "link": "https://github.com/cst1229/"
    },
    {
      "name": "DNin01",
      "link": "https://github.com/DNin01"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    },
    {
      "url": "disable-wobble.css",
      "if": {
        "settings": {
          "mode": "no-wobble"
        }
      }
    }
  ],
  "settings": [
    {
      "id": "mode",
      "name": "Mode",
      "type": "select",
      "potentialValues": [
        {
          "id": "none",
          "name": "Fix bug"
        },
        {
          "id": "no-wobble",
          "name": "Fix bug and disable sprite wobble"
        }
      ],
      "default": "none"
    }
  ],
  "tags": [
    "recommended",
    "new"
  ],
  "enabledByDefault": true,
  "dynamicDisable": true
};
export default manifest;
