/* generated by pull.js */
import _css from "!css-loader!./userstyle.css";
import _css2 from "!css-loader!./disable-wobble.css";
export const resources = {
  "userstyle.css": _css,
  "disable-wobble.css": _css2,
};
