/* generated by pull.js */
import _js from "./bubbles.js";
import _js2 from "./paper.js";
import _js3 from "./extension_icons.js";
import _js4 from "./zoom_icons.js";
import _js5 from "./paint_icons.js";
import _js6 from "./dial.js";
import _js7 from "./debugger.js";
import _css from "!css-loader!./experimental_editor.css";
import _css2 from "!css-loader!./paper.css";
import _css3 from "!css-loader!./stage.css";
import _css4 from "!css-loader!./stage_compact_scrollbars.css";
import _asset from "!url-loader!./assets/translate_white.svg";
export const resources = {
  "bubbles.js": _js,
  "paper.js": _js2,
  "extension_icons.js": _js3,
  "zoom_icons.js": _js4,
  "paint_icons.js": _js5,
  "dial.js": _js6,
  "debugger.js": _js7,
  "experimental_editor.css": _css,
  "paper.css": _css2,
  "stage.css": _css3,
  "stage_compact_scrollbars.css": _css4,
  "assets\\translate_white.svg": _asset,
};
