/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./style.css";
import _asset from "!url-loader!./lock.svg";
import _asset2 from "!url-loader!./unlock.svg";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "lock.svg": _asset,
  "unlock.svg": _asset2,
};
