/* generated by pull.js */
const manifest = {
  "name": "Sticky footer",
  "description": "Makes the website footer stick out slightly from the bottom of the window and makes it expand when hovering over it, allowing it to be quickly accessed from anywhere on the page.",
  "credits": [
    {
      "name": "Samq64",
      "link": "https://github.com/Samq64"
    },
    {
      "name": "ZenithKnight"
    }
  ],
  "info": [
    {
      "id": "firefoxMobileBug",
      "text": "On Firefox for Android, this addon may work better if the \"Scroll to hide toolbar\" option in Firefox settings → Customize is turned off."
    }
  ],
  "customCssVariables": [
    {
      "name": "expandSpeed",
      "value": {
        "type": "map",
        "source": {
          "type": "settingValue",
          "settingId": "speed"
        },
        "options": {
          "short": "0.25s",
          "default": "0.5s",
          "long": "0.75s"
        }
      }
    }
  ],
  "settings": [
    {
      "name": "Animation speed",
      "id": "speed",
      "type": "select",
      "potentialValues": [
        {
          "id": "short",
          "name": "Quick"
        },
        {
          "id": "default",
          "name": "Default"
        },
        {
          "id": "long",
          "name": "Slow"
        }
      ],
      "default": "default"
    },
    {
      "name": "Only on infinite scrolling pages",
      "id": "infiniteScroll",
      "type": "boolean",
      "if": {
        "addonEnabled": [
          "infinite-scroll"
        ]
      },
      "default": false
    }
  ],
  "userscripts": [],
  "userstyles": [],
  "tags": [
    "new"
  ],
  "dynamicDisable": true
};
export default manifest;
