/* generated by pull.js */
const manifest = {
  "name": "Thumbnail uploader",
  "description": "Adds a dropdown next to the \"Set Thumbnail\" button on the project page to set the thumbnail of your project to any image (including gifs).",
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userscript.css"
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "recommended",
    "new"
  ]
};
export default manifest;
