/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./userscript.css";
import _asset from "!url-loader!./upload.svg";
export const resources = {
  "userscript.js": _js,
  "userscript.css": _css,
  "upload.svg": _asset,
};
