/* generated by pull.js */
const manifest = {
  "name": "Larger \"Save Now\" button",
  "description": "Extends the size of the \"Save Now\" button in the editor, making it easier to click.",
  "tags": [
    "recommended",
    "new"
  ],
  "enabledByDefault": true,
  "credits": [
    {
      "name": "BroJac5246",
      "link": "https://github.com/BroJac5246/"
    }
  ],
  "dynamicDisable": true,
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ]
};
export default manifest;
