/* generated by pull.js */
const manifest = {
  "name": "Show exact count",
  "description": "Shows exact numbers on profiles and the exact project count in studios.",
  "credits": [
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber/"
    },
    {
      "name": "Maximouse",
      "link": "https://mxmou.github.io/exactcount"
    },
    {
      "name": "World_Languages"
    }
  ],
  "info": [
    {
      "id": "studioClick",
      "text": "To see the exact number of projects in a studio, enable the \"exact count for studios\" setting below and click the \"100+\" label on the studio's Projects tab."
    }
  ],
  "settings": [
    {
      "name": "Exact counts for profiles",
      "id": "user",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Exact count for studios",
      "id": "studio",
      "type": "boolean",
      "default": true
    }
  ],
  "userscripts": [],
  "userstyles": [],
  "dynamicDisable": true,
  "tags": [
    "recommended",
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
