/* generated by pull.js */
const manifest = {
  "name": "Do not automatically run duplicated blocks",
  "description": "Fixes a bug in the Scratch editor, where duplicating a block and attaching it to a script causes the script to run.",
  "credits": [
    {
      "name": "lisa_wolfgang",
      "link": "https://github.com/lisa-wolfgang"
    },
    {
      "name": "GarboMuffin",
      "link": "https://github.com/GarboMuffin"
    },
    {
      "name": "apple502j",
      "link": "https://github.com/apple502j"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "recommended",
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
