/* generated by pull.js */
const manifest = {
  "name": "Remix own projects",
  "description": "Adds the Remix button to your own projects.",
  "credits": [
    {
      "name": "Weredime (9gr)",
      "link": "https://scratch.mit.edu/users/9gr/"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "new"
  ],
  "dynamicDisable": true
};
export default manifest;
