/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./search-bar.css";
import _asset from "!url-loader!./reset-icon.svg";
import _asset2 from "!url-loader!./search-icon.svg";
export const resources = {
  "userscript.js": _js,
  "search-bar.css": _css,
  "reset-icon.svg": _asset,
  "search-icon.svg": _asset2,
};
