/* generated by pull.js */
const manifest = {
  "name": "FPS counter",
  "description": "Adds an FPS counter above the stage.",
  "credits": [
    {
      "name": "Tacodiva",
      "link": "https://github.com/Tacodiva"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "tags": [
    "new"
  ],
  "relatedAddons": [
    "clones",
    "debugger"
  ]
};
export default manifest;
