/* generated by pull.js */
const manifest = {
  "name": "Feature unshared projects",
  "description": "Allows you to choose unshared projects after clicking \"change featured project\" in your profile.",
  "credits": [
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber/"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [],
  "tags": [
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
