/* generated by pull.js */
const manifest = {
  "name": "Dango rain on profiles (April Fools Day)",
  "description": "Users that include the word \"dango\" on their \"About Me\" will have dango emojis raining on the sides of their profile.",
  "info": [
    {
      "type": "notice",
      "text": "Only Scratch Addons users with this enabled will see the dango rain.",
      "id": "OnlyScratchAddonsUsers"
    }
  ],
  "credits": [
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber/"
    },
    {
      "name": "World_Languages",
      "link": "https://scratch.mit.edu/users/World_Languages/"
    },
    {
      "name": "griffpatch",
      "link": "https://scratch.mit.edu/users/griffpatch/"
    }
  ],
  "userscripts": [],
  "userstyles": [],
  "tags": [
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
