/* generated by pull.js */
const manifest = {
  "name": "Jump to custom block definition",
  "description": "Jump to a custom block's definition by middle-clicking or Shift+clicking on the block or selecting \"Go to Definition\" in the right click context menu.",
  "credits": [
    {
      "name": "griffpatch"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "recommended",
    "new"
  ],
  "enabledByDefault": true,
  "dynamicDisable": true
};
export default manifest;
