/* generated by pull.js */
const manifest = {
  "name": "True forums YouTube links",
  "description": "Replaces links to the embedded site with real YouTube links.",
  "credits": [
    {
      "name": "HTML-Fan/NT"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "relatedAddons": [
    "youtube-fullscreen"
  ],
  "enabledByDefault": false
};
export default manifest;
