/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./style.css";
import _asset from "!url-loader!./icon.svg";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "icon.svg": _asset,
};
