/* generated by pull.js */
const manifest = {
  "name": "Preview project instructions and notes",
  "description": "In your own projects, adds a toggle above the Instructions field to preview the project instructions and notes as seen by other users.",
  "credits": [
    {
      "name": "Steve0Greatness",
      "link": "https://scratch.mit.edu/users/Steve0Greatness"
    },
    {
      "name": "World_Languages"
    }
  ],
  "tags": [
    "new"
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "dynamicDisable": true
};
export default manifest;
