/* generated by pull.js */
const manifest = {
  "name": "Highlight project creator in comments",
  "description": "Adds a badge next to the project creator in project comments sections. Also adds a badge next to the original poster in forum topics.",
  "tags": [
    "new"
  ],
  "enabledByDefault": false,
  "userscripts": [
    {
      "url": "projects.js"
    }
  ],
  "userstyles": [
    {
      "url": "projectpage.css"
    }
  ],
  "credits": [
    {
      "name": "MDWalters",
      "link": "https://scratch.mit.edu/users/MDWalters/"
    },
    {
      "name": "World_Languages"
    }
  ]
};
export default manifest;
