/* generated by pull.js */
const manifest = {
  "name": "Sprite and script count",
  "description": "Shows the number of sprites and scripts a project has next to the Remix button.",
  "tags": [
    "new"
  ],
  "relatedAddons": [
    "block-count"
  ],
  "credits": [
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber/"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "projectstats.js"
    }
  ],
  "userstyles": [
    {
      "url": "userscript.css"
    },
    {
      "url": "text-only.css",
      "if": {
        "settings": {
          "show": "text"
        }
      }
    }
  ],
  "settings": [
    {
      "name": "Appearance",
      "id": "show",
      "type": "select",
      "potentialValues": [
        {
          "id": "both",
          "name": "Icon and text"
        },
        {
          "id": "icon",
          "name": "Icon only"
        },
        {
          "id": "text",
          "name": "Text only"
        }
      ],
      "default": "both"
    }
  ]
};
export default manifest;
