/* generated by pull.js */
import _js from "./projectstats.js";
import _css from "!css-loader!./userscript.css";
import _css2 from "!css-loader!./text-only.css";
export const resources = {
  "projectstats.js": _js,
  "userscript.css": _css,
  "text-only.css": _css2,
};
