/* generated by pull.js */
import _css from "!css-loader!./menu-icons.css";
import _css2 from "!css-loader!./menu-labels.css";
export const resources = {
  "menu-icons.css": _css,
  "menu-labels.css": _css2,
};
