/* generated by pull.js */
const manifest = {
  "name": "SVG uploads fix",
  "description": "Fixes a bug in the Scratch editor that makes uploaded SVG files created with some image editors, such as Affinity Designer, broken.",
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "enabledByDefault": true
};
export default manifest;
