/* generated by pull.js */
const manifest = {
  "name": "Modify version information on forums",
  "description": "Changes the text \"Flash version\" to \"Flash versions\" when clicking the globe icon on the forums.",
  "info": [
    {
      "text": "This is useful for Scratch Addons developers to see if a bug that was reported on the forums was possibly caused by the extension.",
      "id": "usefulness"
    }
  ],
  "userscripts": [],
  "tags": [
    "new"
  ],
  "enabledByDefault": true
};
export default manifest;
