/* generated by pull.js */
const manifest = {
  "name": "Scratch 3.0 → 2.0",
  "description": "Makes Scratch 3.0-styled pages look like Scratch 2.0.",
  "tags": [
    "theme"
  ],
  "relatedAddons": [
    "scratchr2",
    "editor-stage-left",
    "editor-buttons-reverse-order",
    "old-studio-layout"
  ],
  "credits": [
    {
      "name": "Maximouse",
      "link": "https://scratch.mit.edu/users/Maximouse/"
    }
  ],
  "dynamicDisable": true,
  "settings": [
    {
      "id": "navbarSeparators",
      "type": "boolean",
      "name": "Separator lines in navigation bar",
      "default": false
    }
  ],
  "userstyles": [
    {
      "url": "main.css"
    },
    {
      "url": "project.css"
    },
    {
      "url": "comments.css"
    }
  ]
};
export default manifest;
