/* generated by pull.js */
import _css from "!css-loader!./main.css";
import _css2 from "!css-loader!./project.css";
import _css3 from "!css-loader!./comments.css";
import _asset from "!url-loader!./assets/embed_logo.png";
import _asset2 from "!url-loader!./assets/embed_logo_hover.png";
import _asset3 from "!url-loader!./assets/full_screen.png";
import _asset4 from "!url-loader!./assets/green_flag.png";
import _asset5 from "!url-loader!./assets/green_flag_60fps.png";
import _asset6 from "!url-loader!./assets/green_flag_60fps_hover.png";
import _asset7 from "!url-loader!./assets/green_flag_gray.png";
import _asset8 from "!url-loader!./assets/green_flag_hover.png";
import _asset9 from "!url-loader!./assets/green_flag_large.png";
import _asset10 from "!url-loader!./assets/pause.svg";
import _asset11 from "!url-loader!./assets/pause_hover.svg";
import _asset12 from "!url-loader!./assets/play.svg";
import _asset13 from "!url-loader!./assets/play_hover.svg";
import _asset14 from "!url-loader!./assets/stop.png";
import _asset15 from "!url-loader!./assets/stop_hover.png";
export const resources = {
  "main.css": _css,
  "project.css": _css2,
  "comments.css": _css3,
  "assets\\embed_logo.png": _asset,
  "assets\\embed_logo_hover.png": _asset2,
  "assets\\full_screen.png": _asset3,
  "assets\\green_flag.png": _asset4,
  "assets\\green_flag_60fps.png": _asset5,
  "assets\\green_flag_60fps_hover.png": _asset6,
  "assets\\green_flag_gray.png": _asset7,
  "assets\\green_flag_hover.png": _asset8,
  "assets\\green_flag_large.png": _asset9,
  "assets\\pause.svg": _asset10,
  "assets\\pause_hover.svg": _asset11,
  "assets\\play.svg": _asset12,
  "assets\\play_hover.svg": _asset13,
  "assets\\stop.png": _asset14,
  "assets\\stop_hover.png": _asset15,
};
