/* generated by pull.js */
const manifest = {
  "name": "Costume editor keyboard shortcuts",
  "description": "Allows switching costumes with Ctrl+Left/Right and selecting tools in the costume editor using keyboard shortcuts (similar to TurboWarp). Hover over a tool to view its shortcut.",
  "credits": [
    {
      "name": "Hollow_Song's Dad",
      "link": "https://scratch.mit.edu/users/Hollow_Song/"
    }
  ],
  "info": [
    {
      "id": "cmdKey",
      "text": "On macOS, use the Cmd key instead of the Ctrl key."
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "recommended",
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
