/* generated by pull.js */
const manifest = {
  "name": "Capitalized Account Settings",
  "description": "Changes \"Account settings\" in the account menu to \"Account Settings\".",
  "userstyles": [],
  "dynamicDisable": true,
  "tags": [
    "new"
  ]
};
export default manifest;
