/* generated by pull.js */
import _asset from "!url-loader!./book_edit.png";
import _asset2 from "!url-loader!./book_open.png";
import _asset3 from "!url-loader!./magnifier.png";
import _asset4 from "!url-loader!./palette.png";
import _asset5 from "!url-loader!./text_align_center.png";
export const resources = {
  "book_edit.png": _asset,
  "book_open.png": _asset2,
  "magnifier.png": _asset3,
  "palette.png": _asset4,
  "text_align_center.png": _asset5,
};
