/* generated by pull.js */
const manifest = {
  "name": "Better forum post editor buttons",
  "description": "Changes the icons for buttons in the forum post editor from pixelated bitmaps to Material icons.",
  "userstyles": [],
  "tags": [
    "theme"
  ],
  "credits": [
    {
      "name": "A-E-",
      "link": "https://github.com/easrng/material-scratch-forum-editor-buttons"
    },
    {
      "name": "Secret-chest",
      "link": "https://github.com/Secret-chest"
    },
    {
      "name": "Google",
      "link": "https://fonts.google.com/icons?icon.set=Material+Icons"
    }
  ],
  "enabledByDefault": false,
  "dynamicDisable": true
};
export default manifest;
