/* generated by pull.js */
import _asset from "!url-loader!./bold.svg";
import _asset2 from "!url-loader!./bullet_list.svg";
import _asset3 from "!url-loader!./center.svg";
import _asset4 from "!url-loader!./clear.svg";
import _asset5 from "!url-loader!./code.svg";
import _asset6 from "!url-loader!./color.svg";
import _asset7 from "!url-loader!./computer.svg";
import _asset8 from "!url-loader!./dictionary.svg";
import _asset9 from "!url-loader!./done.svg";
import _asset10 from "!url-loader!./expand.svg";
import _asset11 from "!url-loader!./google.svg";
import _asset12 from "!url-loader!./image.svg";
import _asset13 from "!url-loader!./italic.svg";
import _asset14 from "!url-loader!./link.svg";
import _asset15 from "!url-loader!./list_item.svg";
import _asset16 from "!url-loader!./number_list.svg";
import _asset17 from "!url-loader!./quote.svg";
import _asset18 from "!url-loader!./scratchblocks.svg";
import _asset19 from "!url-loader!./size.svg";
import _asset20 from "!url-loader!./smiley.svg";
import _asset21 from "!url-loader!./strikethrough.svg";
import _asset22 from "!url-loader!./underlined.svg";
import _asset23 from "!url-loader!./wp.svg";
export const resources = {
  "bold.svg": _asset,
  "bullet_list.svg": _asset2,
  "center.svg": _asset3,
  "clear.svg": _asset4,
  "code.svg": _asset5,
  "color.svg": _asset6,
  "computer.svg": _asset7,
  "dictionary.svg": _asset8,
  "done.svg": _asset9,
  "expand.svg": _asset10,
  "google.svg": _asset11,
  "image.svg": _asset12,
  "italic.svg": _asset13,
  "link.svg": _asset14,
  "list_item.svg": _asset15,
  "number_list.svg": _asset16,
  "quote.svg": _asset17,
  "scratchblocks.svg": _asset18,
  "size.svg": _asset19,
  "smiley.svg": _asset20,
  "strikethrough.svg": _asset21,
  "underlined.svg": _asset22,
  "wp.svg": _asset23,
};
