/* generated by pull.js */
const manifest = {
  "name": "Profile page banner",
  "description": "Turns the featured project on any user's profile into a nice-looking banner.",
  "credits": [
    {
      "name": "Wicycool",
      "link": "https://wicy.cool/"
    }
  ],
  "userscripts": [],
  "userstyles": [],
  "settings": [
    {
      "id": "blur",
      "name": "Banner blur",
      "type": "integer",
      "min": 0,
      "max": 5,
      "default": 0
    }
  ],
  "tags": []
};
export default manifest;
