/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Save blocks as image",
  "description": "Right click on the code area or a stack of blocks to copy it to the clipboard or save it as a PNG or SVG file.",
  "tags": [
    "new"
  ],
  "relatedAddons": [
    "mediarecorder"
  ],
  "credits": [
    {
      "name": "summerscar"
    },
    {
      "name": "Jazza",
      "link": "https://scratch.mit.edu/users/greeny--231"
    },
    {
      "name": "World_Languages"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "enabledByDefault": false
};
import {clipboardSupported} from "../../environment";
if (!clipboardSupported) manifest.unsupported = true;
export default manifest;
