/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./style.css";
import _asset from "!url-loader!./copy.svg";
import _asset2 from "!url-loader!./download.svg";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "copy.svg": _asset,
  "download.svg": _asset2,
};
