/* generated by pull.js */
const manifest = {
  "name": "Customizable navigation bar",
  "description": "Choose a list of links to be displayed in the navigation bar.",
  "userscripts": [
    {
      "url": "items_scratchwww.js"
    },
    {
      "url": "compact_scratchwww.js"
    }
  ],
  "userstyles": [],
  "settings": [
    {
      "name": "Items",
      "id": "items",
      "type": "table",
      "default": [
        {
          "name": "Create",
          "url": "/projects/editor/"
        },
        {
          "name": "Explore",
          "url": "/explore/projects/all"
        },
        {
          "name": "Ideas",
          "url": "/ideas"
        }
      ],
      "row": [
        {
          "name": "Name",
          "id": "name",
          "type": "string",
          "default": ""
        },
        {
          "name": "URL",
          "id": "url",
          "type": "untranslated",
          "default": ""
        }
      ],
      "presets": [
        {
          "name": "Create",
          "values": {
            "name": "Create",
            "url": "/projects/editor/"
          }
        },
        {
          "name": "Explore",
          "values": {
            "name": "Explore",
            "url": "/explore/projects/all"
          }
        },
        {
          "name": "Ideas",
          "values": {
            "name": "Ideas",
            "url": "/ideas"
          }
        },
        {
          "name": "About",
          "values": {
            "name": "About",
            "url": "/about"
          }
        },
        {
          "name": "Discuss",
          "values": {
            "name": "Discuss",
            "url": "/discuss"
          }
        },
        {
          "name": "Wiki",
          "values": {
            "name": "Wiki",
            "url": "https://scratch-wiki.info/"
          }
        }
      ]
    },
    {
      "name": "Show Membership link when logged out",
      "id": "showMembership",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Compact user dropdown",
      "id": "compact-nav",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Stick to",
      "id": "stick",
      "type": "select",
      "default": "screen",
      "potentialValues": [
        {
          "id": "screen",
          "name": "Top of screen"
        },
        {
          "id": "page",
          "name": "Top of page"
        }
      ]
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "relatedAddons": [
    "custom-menu-bar",
    "expanding-search-bar"
  ],
  "enabledByDefault": false
};
export default manifest;
