/* generated by pull.js */
import _js from "./items_scratchwww.js";
import _js2 from "./compact_scratchwww.js";
export const resources = {
  "items_scratchwww.js": _js,
  "compact_scratchwww.js": _js2,
};
