/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./style.css";
import _css2 from "!css-loader!./gamepadlib.css";
import _asset from "!url-loader!./active.png";
import _asset2 from "!url-loader!./close.svg";
import _asset3 from "!url-loader!./cursor.png";
import _asset4 from "!url-loader!./dot.svg";
import _asset5 from "!url-loader!./gamepad.svg";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "gamepadlib.css": _css2,
  "active.png": _asset,
  "close.svg": _asset2,
  "cursor.png": _asset3,
  "dot.svg": _asset4,
  "gamepad.svg": _asset5,
};
