/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./common.css";
import _css2 from "!css-loader!./90s.css";
import _css3 from "!css-loader!./oldtimey.css";
import _css4 from "!css-loader!./prehistoric.css";
import _css5 from "!css-loader!./mystery.css";
import _asset from "!url-loader!./assets/90s-logo.svg";
import _asset2 from "!url-loader!./assets/90s-shapes.svg";
import _asset3 from "!url-loader!./assets/oldtimey-logo.svg";
import _asset4 from "!url-loader!./assets/prehistoric-logo.svg";
export const resources = {
  "userscript.js": _js,
  "common.css": _css,
  "90s.css": _css2,
  "oldtimey.css": _css3,
  "prehistoric.css": _css4,
  "mystery.css": _css5,
  "assets\\90s-logo.svg": _asset,
  "assets\\90s-shapes.svg": _asset2,
  "assets\\oldtimey-logo.svg": _asset3,
  "assets\\prehistoric-logo.svg": _asset4,
};
