/* generated by pull.js */
const manifest = {
  "name": "Show project thumbnail while loading",
  "description": "Shows the project's thumbnail as a placeholder before the project is started and while it loads.",
  "credits": [
    {
      "name": "Samq64",
      "link": "https://github.com/Samq64"
    },
    {
      "name": "Maximouse",
      "link": "https://scratch.mit.edu/users/Maximouse/"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    },
    {
      "url": "scratch3to2.css",
      "if": {
        "addonEnabled": [
          "scratch3to2"
        ]
      }
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "settings": [
    {
      "name": "Darken thumbnail (%)",
      "id": "darken",
      "type": "integer",
      "min": 10,
      "max": 90,
      "default": 25
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "theme",
    "new"
  ]
};
export default manifest;
