/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./userstyle.css";
import _css2 from "!css-loader!./scratch3to2.css";
export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css,
  "scratch3to2.css": _css2,
};
