/* generated by pull.js */
const manifest = {
  "name": "Disable search bar autocomplete",
  "description": "Stops web browsers from autocompleting suggestions in the navigation bar's search bar.",
  "tags": [
    "new"
  ],
  "credits": [
    {
      "name": "BroJac5246",
      "link": "https://github.com/BroJac5246/"
    }
  ],
  "dynamicDisable": true,
  "userscripts": []
};
export default manifest;
