/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./standalone-edit.css";
import _css2 from "!css-loader!./scroll.css";
export const resources = {
  "userscript.js": _js,
  "standalone-edit.css": _css,
  "scroll.css": _css2,
};
