/* generated by pull.js */
const manifest = {
  "name": "ocular integration",
  "description": "Shows ocular statuses and forum post reactions. Uses my-ocular.jeffalo.net to obtain data.",
  "credits": [
    {
      "name": "Jeffalo",
      "link": "https://github.com/jeffalo"
    }
  ],
  "userscripts": [],
  "userstyles": [],
  "dynamicDisable": true,
  "settings": [
    {
      "name": "Show statuses on profiles",
      "id": "profile",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Show statuses on forums",
      "id": "discuss",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Show statuses on...",
      "id": "show-status",
      "type": "select",
      "potentialValues": [
        {
          "id": "everywhere",
          "name": "All profiles"
        },
        {
          "id": "others",
          "name": "Others' profiles only"
        }
      ],
      "default": "everywhere"
    },
    {
      "name": "Show reaction buttons and \"View on ocular\" link",
      "id": "reactions",
      "type": "boolean",
      "default": true
    }
  ],
  "tags": [
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
