/* eslint-disable import/no-nodejs-modules */
/* eslint-disable import/no-commonjs */
/* global __dirname */

const fs = require('fs');
const pathUtil = require('path');

/**
 * 遍历目录获得一级子目录名称
 * @param {string} dir 目录路径
 * @returns {string[]} 一级子目录名称
 */
const walkFirstDir = dir => {
    const children = fs.readdirSync(dir);
    const files = [];
    for (const child of children) {
        const path = pathUtil.join(dir, child);
        const stat = fs.statSync(path);
        if (stat.isDirectory()) {
            files.push(child);
        }
    }
    return files;
};

const addonsDir = pathUtil.resolve(__dirname, 'addons');
const addons = walkFirstDir(addonsDir);

const wrap = content => `/* generated by pull.js */
const manifest = ${content};
export default manifest;
`;

for (const addon of addons) {
    const addonPath = pathUtil.resolve(addonsDir, addon, '_manifest_entry.js');
    let content;
    try {
        content = require(addonPath).default;
    } catch (e) {
        console.error(addon, '引入出错:', e);
        continue;
    }
    if (content.tags.includes('recommended')) {
        content.enabledByDefault = true;
        fs.writeFileSync(addonPath, wrap(JSON.stringify(content, null, 4)));
    }
}
