/* generated by pull.js */
const manifest = {
  "name": "Confirmations",
  "description": "Asks if you're sure when committing actions under your Scratch account, such as sharing projects.",
  "credits": [
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber/"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [],
  "settings": [
    {
      "name": "Confirm project sharing",
      "id": "projectsharing",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Confirm project unsharing",
      "id": "projectunsharing",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Confirm deleting projects",
      "id": "removingprojects",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Confirm canceling comments",
      "id": "cancelcomment",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Confirm following/unfollowing users",
      "id": "followinguser",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Confirm joining studios",
      "id": "joiningstudio",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Confirm closing forum topics",
      "id": "closingtopic",
      "type": "boolean",
      "default": false
    }
  ],
  "tags": [
    "recommended",
    "new"
  ],
  "relatedAddons": [
    "no-sprite-confirm"
  ],
  "enabledByDefault": false
};
export default manifest;
