/* generated by pull.js */
const manifest = {
  "name": "Customizable profile picture border",
  "description": "Allows you to hide or change the outline around profile pictures in project and studio comments.",
  "credits": [
    {
      "name": "CST1229",
      "link": "https://github.com/CST1229"
    }
  ],
  "userstyles": [
    {
      "url": "hide_outline.css",
      "if": {
        "settings": {
          "hide-outline": true
        }
      }
    },
    {
      "url": "outline_color.css",
      "if": {
        "settings": {
          "hide-outline": false
        }
      }
    },
    {
      "url": "fill_transparent.css",
      "if": {
        "settings": {
          "fill-transparent": true
        }
      }
    }
  ],
  "dynamicDisable": true,
  "settings": [
    {
      "name": "Hide outline",
      "id": "hide-outline",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Fill transparent profile pictures",
      "id": "fill-transparent",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Outline color",
      "id": "outline-color",
      "type": "color",
      "allowTransparency": true,
      "default": "#4d97ff40",
      "if": {
        "settings": {
          "hide-outline": false,
          "fill-transparent": true
        }
      }
    }
  ],
  "tags": [
    "theme"
  ],
  "enabledByDefault": false
};
export default manifest;
