/* generated by pull.js */
import _css from "!css-loader!./hide_outline.css";
import _css2 from "!css-loader!./outline_color.css";
import _css3 from "!css-loader!./fill_transparent.css";
export const resources = {
  "hide_outline.css": _css,
  "outline_color.css": _css2,
  "fill_transparent.css": _css3,
};
