/* generated by pull.js */
import _css from "!css-loader!./experimental_scratchwww.css";
import _css2 from "!css-loader!./banners/darker.css";
import _css3 from "!css-loader!./banners/desaturated.css";
import _asset from "!url-loader!./assets/caret_transparent.svg";
import _asset2 from "!url-loader!./assets/caret_transparent_hover.svg";
import _asset3 from "!url-loader!./assets/caret_white.svg";
import _asset4 from "!url-loader!./assets/caret_white_hover.svg";
import _asset5 from "!url-loader!./assets/favorite_transparent.svg";
import _asset6 from "!url-loader!./assets/forum_buttons/bold.png";
import _asset7 from "!url-loader!./assets/forum_buttons/browser_os.png";
import _asset8 from "!url-loader!./assets/forum_buttons/center.png";
import _asset9 from "!url-loader!./assets/forum_buttons/italic.png";
import _asset10 from "!url-loader!./assets/forum_buttons/list_bullet.png";
import _asset11 from "!url-loader!./assets/forum_buttons/list_item.png";
import _asset12 from "!url-loader!./assets/forum_buttons/list_numeric.png";
import _asset13 from "!url-loader!./assets/forum_buttons/stroke.png";
import _asset14 from "!url-loader!./assets/forum_buttons/underline.png";
import _asset15 from "!url-loader!./assets/gobo.png";
import _asset16 from "!url-loader!./assets/love_transparent.svg";
import _asset17 from "!url-loader!./assets/meow.png";
import _asset18 from "!url-loader!./assets/waffle.png";
export const resources = {
  "experimental_scratchwww.css": _css,
  "banners/darker.css": _css2,
  "banners/desaturated.css": _css3,
  "assets\\caret_transparent.svg": _asset,
  "assets\\caret_transparent_hover.svg": _asset2,
  "assets\\caret_white.svg": _asset3,
  "assets\\caret_white_hover.svg": _asset4,
  "assets\\favorite_transparent.svg": _asset5,
  "assets\\forum_buttons\\bold.png": _asset6,
  "assets\\forum_buttons\\browser_os.png": _asset7,
  "assets\\forum_buttons\\center.png": _asset8,
  "assets\\forum_buttons\\italic.png": _asset9,
  "assets\\forum_buttons\\list_bullet.png": _asset10,
  "assets\\forum_buttons\\list_item.png": _asset11,
  "assets\\forum_buttons\\list_numeric.png": _asset12,
  "assets\\forum_buttons\\stroke.png": _asset13,
  "assets\\forum_buttons\\underline.png": _asset14,
  "assets\\gobo.png": _asset15,
  "assets\\love_transparent.svg": _asset16,
  "assets\\meow.png": _asset17,
  "assets\\waffle.png": _asset18,
};
