/* generated by pull.js */
const manifest = {
  "name": "Project progress bar",
  "description": "Adds a progress bar for loading and saving projects.",
  "credits": [
    {
      "name": "GarboMuffin"
    },
    {
      "name": "BroJac5246",
      "link": "https://github.com/BroJac5246/"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "settings": [
    {
      "name": "Show progress bar at top of page",
      "id": "topbar",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Progress bar height (px)",
      "id": "height",
      "type": "integer",
      "min": 3,
      "max": 25,
      "default": 8
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "recommended",
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
