/* generated by pull.js */
const manifest = {
  "name": "Line breaks in comments",
  "description": "Makes line breaks (pressing Enter) in comments on the website visible instead of converting them to spaces.",
  "credits": [
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber/"
    }
  ],
  "info": [
    {
      "type": "notice",
      "text": "Line breaks are only visible to users with this addon enabled. They will appear as spaces for others.",
      "id": "ownLineBreaks"
    },
    {
      "type": "info",
      "text": "On profile pages, line breaks at the beginning or end of a comment do not appear.",
      "id": "scratchr2Linebreaks"
    }
  ],
  "userscripts": [],
  "userstyles": [
    {
      "url": "break-spaces.css"
    },
    {
      "url": "scrollbars.css",
      "if": {
        "settings": {
          "scrollbars": true
        }
      }
    }
  ],
  "settings": [
    {
      "name": "Add scroll bars to tall comments",
      "id": "scrollbars",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Maximum number of lines visible at once",
      "id": "height",
      "type": "integer",
      "min": 1,
      "max": 100,
      "default": 5,
      "if": {
        "settings": {
          "scrollbars": true
        }
      }
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "new"
  ]
};
export default manifest;
