/* generated by pull.js */
import _css from "!css-loader!./break-spaces.css";
import _css2 from "!css-loader!./scrollbars.css";
export const resources = {
  "break-spaces.css": _css,
  "scrollbars.css": _css2,
};
