/* generated by pull.js */
const manifest = {
  "name": "Better forum quoter",
  "description": "Select text in a forum post and click quote in the bottom right corner to only quote the selected text.",
  "credits": [
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber/"
    },
    {
      "name": "pufferfish101007",
      "link": "https://scratch.mit.edu/users/pufferfish101007/"
    }
  ],
  "userscripts": [],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "info": [
    {
      "type": "notice",
      "text": "The BBCode may not be 100% accurate. To get fully accurate quotes, quote as normal and delete any parts that you don't need.",
      "id": "scratchblocks_notice"
    }
  ]
};
export default manifest;
