/* generated by pull.js */
const manifest = {
  "name": "Echo effect button",
  "description": "Brings back the Echo button in the sound editor.",
  "tags": [
    "new"
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ]
};
export default manifest;
