/* generated by pull.js */
const manifest = {
  "name": "One-click studio invites",
  "description": "Accept studio invites directly from Scratch's messages page. An accept button will appear below studio invite messages.",
  "credits": [
    {
      "name": "Weredime (9gr)",
      "link": "https://scratch.mit.edu/users/9gr/"
    }
  ],
  "userscripts": [],
  "userstyles": [],
  "tags": [
    "new"
  ],
  "dynamicDisable": true
};
export default manifest;
