/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./style.css";
import _asset from "!url-loader!./icons/close.svg";
import _asset2 from "!url-loader!./icons/debug.svg";
import _asset3 from "!url-loader!./icons/delete.svg";
import _asset4 from "!url-loader!./icons/download-white.svg";
import _asset5 from "!url-loader!./icons/error.svg";
import _asset6 from "!url-loader!./icons/logs.svg";
import _asset7 from "!url-loader!./icons/performance.svg";
import _asset8 from "!url-loader!./icons/play.svg";
import _asset9 from "!url-loader!./icons/step.svg";
import _asset10 from "!url-loader!./icons/subthread.svg";
import _asset11 from "!url-loader!./icons/threads.svg";
import _asset12 from "!url-loader!./icons/warning.svg";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "icons/close.svg": _asset,
  "icons/debug.svg": _asset2,
  "icons/delete.svg": _asset3,
  "icons/download-white.svg": _asset4,
  "icons/error.svg": _asset5,
  "icons/logs.svg": _asset6,
  "icons/performance.svg": _asset7,
  "icons/play.svg": _asset8,
  "icons/step.svg": _asset9,
  "icons/subthread.svg": _asset10,
  "icons/threads.svg": _asset11,
  "icons/warning.svg": _asset12,
};
