/* generated by pull.js */
const manifest = {
  "name": "Replace backpack bar with button",
  "description": "Replaces the backpack bar along the bottom of the editor with a button next to the zoom controls.",
  "credits": [
    {
      "name": "Norbiros",
      "link": "https://scratch.mit.edu/users/norbir/"
    },
    {
      "name": "Maximouse",
      "link": "https://scratch.mit.edu/users/Maximouse/"
    }
  ],
  "userstyles": [
    {
      "url": "border.css"
    },
    {
      "url": "button.css"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "new"
  ],
  "dynamicDisable": true,
  "enabledByDefault": false
};
export default manifest;
