/* generated by pull.js */
const manifest = {
  "name": "Scratch 2.0 → 3.0",
  "description": "Makes Scratch 2.0-styled pages look like Scratch 3.0.",
  "tags": [
    "theme",
    "recommended"
  ],
  "relatedAddons": [
    "scratch3to2"
  ],
  "credits": [
    {
      "name": "Maximouse",
      "link": "https://scratch.mit.edu/users/Maximouse/"
    }
  ],
  "customCssVariables": [
    {
      "name": "defaultLinkIconFilter",
      "value": {
        "type": "recolorFilter",
        "source": "#855cd6"
      }
    }
  ],
  "dynamicDisable": true,
  "userscripts": [],
  "userstyles": [],
  "settings": [
    {
      "name": "Forum post style",
      "id": "postStyle",
      "type": "select",
      "potentialValues": [
        {
          "id": "box",
          "name": "Box"
        },
        {
          "id": "bubble",
          "name": "Bubble"
        }
      ],
      "default": "box"
    }
  ]
};
export default manifest;
