/* generated by pull.js */
import _asset from "!url-loader!./assets/caret.svg";
import _asset2 from "!url-loader!./assets/caret_hover.svg";
import _asset3 from "!url-loader!./assets/dots.svg";
import _asset4 from "!url-loader!./assets/dots_first.svg";
import _asset5 from "!url-loader!./assets/zoom_in.svg";
import _asset6 from "!url-loader!./assets/zoom_out.svg";
import _asset7 from "!url-loader!./assets/zoom_reset.svg";
export const resources = {
  "assets\\caret.svg": _asset,
  "assets\\caret_hover.svg": _asset2,
  "assets\\dots.svg": _asset3,
  "assets\\dots_first.svg": _asset4,
  "assets\\zoom_in.svg": _asset5,
  "assets\\zoom_out.svg": _asset6,
  "assets\\zoom_reset.svg": _asset7,
};
