/* generated by pull.js */
const manifest = {
  "name": "Project page download button",
  "description": "Allows you to download projects directly from the project page, without having to open the editor first. The Download button is added next to the Copy Link button.",
  "tags": [
    "new"
  ],
  "credits": [
    {
      "name": "Jazza",
      "link": "https://scratch.mit.edu/users/greeny--231"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "dynamicDisable": true
};
export default manifest;
