/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Move sprite to front layer",
  "description": "Move a sprite to the front (top layer) of the stage from its context menu or by Shift+Clicking it.",
  "credits": [
    {
      "name": "Norbiros",
      "link": "https://scratch.mit.edu/users/Norbir/"
    },
    {
      "name": "s_federici",
      "link": "https://scratch.mit.edu/users/s_federici/"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "new"
  ]
};
export default manifest;
