/* generated by pull.js */
const manifest = {
  "name": "Live forum post preview",
  "description": "Automatically shows a preview when you stop typing while writing or editing a forum post.",
  "credits": [
    {
      "name": "Maximouse",
      "link": "https://scratch.mit.edu/users/Maximouse/"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [],
  "userstyles": [],
  "settings": [
    {
      "name": "Refresh rate",
      "id": "rate",
      "type": "select",
      "potentialValues": [
        {
          "id": "slow",
          "name": "Slow"
        },
        {
          "id": "default",
          "name": "Default"
        },
        {
          "id": "fast",
          "name": "Fast"
        }
      ],
      "default": "default"
    }
  ],
  "tags": [
    "new"
  ]
};
export default manifest;
