/* generated by pull.js */
const manifest = {
  "name": "Forum search",
  "description": "Adds a post search bar to the forums. Uses ScratchDB for information.",
  "credits": [
    {
      "name": "DatOneLefty"
    },
    {
      "name": "Hans5958"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [],
  "userstyles": [],
  "tags": [
    "beta",
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
