/* generated by pull.js */
const manifest = {
  "name": "Longer \"What I'm Working On\"",
  "description": "Allows you to type 55 more characters in your profile's \"What I'm Working On\". Everyone on Scratch will see the extra characters.",
  "credits": [
    {
      "name": "cobalt",
      "link": "https://github.com/cobaltt7"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [],
  "tags": [
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
