/* generated by pull.js */
const manifest = {
  "name": "Compact messages",
  "description": "Makes Scratch's messages page more compact and easier to read.",
  "credits": [
    {
      "name": "yes-i-am-lanky",
      "link": "https://scratch.mit.edu/users/yes-i-am-lanky/"
    },
    {
      "name": "DNin01",
      "link": "https://github.com/DNin01"
    }
  ],
  "settings": [
    {
      "name": "Hide message type icons",
      "id": "hide_icons",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Remove borders",
      "id": "no_borders",
      "type": "boolean",
      "default": false
    },
    {
      "name": "Message padding (px)",
      "id": "message_padding",
      "type": "integer",
      "default": 5,
      "min": 0,
      "max": 16
    },
    {
      "name": "Comment box padding (px)",
      "id": "comment_padding",
      "type": "integer",
      "default": 5,
      "min": 0,
      "max": 16
    }
  ],
  "addonPreview": true,
  "userstyles": [],
  "dynamicDisable": true,
  "tags": [
    "theme"
  ],
  "relatedAddons": [
    "editor-compact"
  ],
  "enabledByDefault": false
};
export default manifest;
