/* generated by pull.js */
const manifest = {
  "name": "Copy code button on forums",
  "description": "Adds a \"copy code\" button above code boxes in forum posts that copies the contents into the clipboard.",
  "credits": [
    {
      "name": "CST1229",
      "link": "https://github.com/CST1229/"
    }
  ],
  "userscripts": [],
  "userstyles": [],
  "dynamicDisable": true,
  "tags": [
    "new"
  ]
};
export default manifest;
