/* generated by pull.js */
const manifest = {
  "name": "Ctrl+Enter to post",
  "description": "Automatically posts the comment or forum post on Ctrl+Enter.",
  "credits": [
    {
      "name": "Weredime (9gr)",
      "link": "https://scratch.mit.edu/users/9gr/"
    }
  ],
  "info": [
    {
      "text": "On macOS, you can also use the Cmd key.",
      "id": "macOS"
    }
  ],
  "settings": [
    {
      "id": "comments",
      "name": "Enable in comments",
      "type": "boolean",
      "default": true
    },
    {
      "id": "forums",
      "name": "Enable on forums",
      "type": "boolean",
      "default": false
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "comments.js",
      "if": {
        "settings": {
          "comments": true
        }
      }
    }
  ],
  "tags": [
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
