/* generated by pull.js */
const manifest = {
  "name": "Featured dangos",
  "description": "A Scratch Addons April Fools joke from 2023 that added a row to the front page featuring dango-related projects.",
  "userscripts": [],
  "userstyles": [],
  "tags": [
    "new"
  ]
};
export default manifest;
