/* generated by pull.js */
import _css from "!css-loader!./monitors.css";
import _css2 from "!css-loader!./monitor-values.css";
export const resources = {
  "monitors.css": _css,
  "monitor-values.css": _css2,
};
