/* generated by pull.js */
const manifest = {
  "name": "Improved dragging of costumes and sounds",
  "description": "When dragging a costume or sound, automatically scrolls the list and fixes a Scratch bug where the dragged item isn't placed at the right position after scrolling.",
  "credits": [
    {
      "name": "mysinginmonsters",
      "link": "https://scratch.mit.edu/users/mysinginmonsters/"
    }
  ],
  "settings": [
    {
      "name": "Auto-scroll speed",
      "id": "scroll-speed",
      "type": "select",
      "description": "Drag and hold a costume or sound at the top or bottom of the list to auto scroll.",
      "potentialValues": [
        {
          "id": "none",
          "name": "Off"
        },
        {
          "id": "slow",
          "name": "Slow"
        },
        {
          "id": "default",
          "name": "Medium"
        },
        {
          "id": "fast",
          "name": "Fast"
        }
      ],
      "default": "default"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "tags": [
    "recommended",
    "new"
  ],
  "enabledByDefault": true,
  "dynamicDisable": true
};
export default manifest;
