/* generated by pull.js */
const manifest = {
  "name": "Redirect to standard forums",
  "description": "Redirects you to the standard (\"main\") view of the forums when you visit the mobile (\"m\") view of the forums, avoiding Page not found errors.",
  "credits": [
    {
      "name": "Weredime (9gr)",
      "link": "https://scratch.mit.edu/users/9gr/"
    }
  ],
  "userscripts": [],
  "tags": [
    "new"
  ],
  "enabledByDefault": true
};
export default manifest;
