/* generated by pull.js */
const manifest = {
  "name": "Share through My Stuff",
  "description": "Share projects through the My Stuff page.",
  "credits": [
    {
      "name": "Steve0Greatness",
      "link": "https://scratch.mit.edu/users/Steve0Greatness/"
    }
  ],
  "userstyles": [],
  "userscripts": [],
  "dynamicDisable": true,
  "tags": [
    "new"
  ],
  "relatedAddons": [
    "editor-unshare-button"
  ],
  "enabledByDefault": false
};
export default manifest;
