/* generated by pull.js */
const manifest = {
  "name": "Disable auto-save",
  "description": "Disables the automatic saving of projects while editing.",
  "info": [
    {
      "type": "warning",
      "text": "This will disable all types of project autosaving. Make sure to manually save your changes frequently to avoid losing them.",
      "id": "manuallysave"
    }
  ],
  "credits": [
    {
      "name": "RustingRobot"
    },
    {
      "name": "DNin01",
      "link": "https://github.com/DNin01"
    },
    {
      "name": "Chrome_Cat",
      "link": "https://scratch.mit.edu/users/Chrome_Cat/"
    }
  ],
  "dynamicDisable": true,
  "userstyles": [
    {
      "url": "modal.css"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "danger",
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
