/* generated by pull.js */
const manifest = {
  "name": "BBCode source button",
  "description": "Adds a button to the forums that shows the BBCode source of a post.",
  "tags": [
    "new"
  ],
  "credits": [
    {
      "name": "Maximouse",
      "link": "https://scratch.mit.edu/users/Maximouse/"
    }
  ],
  "userscripts": [],
  "dynamicDisable": true
};
export default manifest;
