/* generated by pull.js */
const manifest = {
  "name": "More items per row",
  "description": "Lets you change the number of items displayed in a single row in a grid of projects, studios, or users.",
  "tags": [
    "new"
  ],
  "credits": [
    {
      "name": "Maximouse",
      "link": "https://scratch.mit.edu/users/Maximouse/"
    }
  ],
  "dynamicDisable": true,
  "userstyles": [],
  "userscripts": [],
  "settings": [
    {
      "id": "search",
      "type": "integer",
      "name": "Explore and search",
      "min": 2,
      "max": 8,
      "default": 4
    },
    {
      "id": "studioProjects",
      "type": "integer",
      "name": "Studio projects",
      "min": 2,
      "max": 6,
      "default": 3
    },
    {
      "id": "studioCurators",
      "type": "integer",
      "name": "Studio curators",
      "min": 2,
      "max": 6,
      "default": 3
    },
    {
      "id": "projects",
      "type": "integer",
      "name": "Project remixes, user shared and favorite projects",
      "min": 3,
      "max": 8,
      "default": 5
    },
    {
      "id": "studios",
      "type": "integer",
      "name": "Project studios, user curated and followed studios",
      "min": 2,
      "max": 8,
      "default": 4
    },
    {
      "id": "users",
      "type": "integer",
      "name": "User followers and following",
      "min": 6,
      "max": 22,
      "default": 11
    }
  ]
};
export default manifest;
