/* generated by pull.js */
const manifest = {
  "name": "Username search",
  "description": "Allows you to go to a user's profile when you search their username.",
  "userscripts": [],
  "userstyles": [],
  "dynamicDisable": true,
  "credits": [
    {
      "name": "Geotale"
    },
    {
      "name": "pufferfish101007"
    },
    {
      "name": "Hexagonal"
    },
    {
      "name": "valmontechno"
    }
  ],
  "tags": [
    "recommended",
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
