/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./../../libraries/common/cs/react-tooltip.css";
export const resources = {
  "userscript.js": _js,
  "../../libraries/common/cs/react-tooltip.css": _css,
};
