/* generated by pull.js */
const manifest = {
  "name": "Better emojis",
  "description": "Replaces the emojis in comments on the website with improved vector designs.",
  "tags": [
    "new"
  ],
  "relatedAddons": [
    "emoji-picker"
  ],
  "credits": [
    {
      "name": "getbent",
      "link": "https://scratch.mit.edu/users/getbent/"
    },
    {
      "name": "kccuber",
      "link": "https://scratch.mit.edu/users/kccuber/"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true,
  "enabledByDefault": false
};
export default manifest;
