/* generated by pull.js */
import _js from "./userscript.js";
import _asset from "!url-loader!./images/aww-cat.svg";
import _asset2 from "!url-loader!./images/cat.svg";
import _asset3 from "!url-loader!./images/cool-cat.svg";
import _asset4 from "!url-loader!./images/fav-it-cat.svg";
import _asset5 from "!url-loader!./images/gobo.svg";
import _asset6 from "!url-loader!./images/huh-cat.svg";
import _asset7 from "!url-loader!./images/lol-cat.svg";
import _asset8 from "!url-loader!./images/love-it-cat.svg";
import _asset9 from "!url-loader!./images/meow.svg";
import _asset10 from "!url-loader!./images/pizza-cat.svg";
import _asset11 from "!url-loader!./images/rainbow-cat.svg";
import _asset12 from "!url-loader!./images/tongue-out-cat.svg";
import _asset13 from "!url-loader!./images/upside-down-cat.svg";
import _asset14 from "!url-loader!./images/waffle.svg";
import _asset15 from "!url-loader!./images/wink-cat.svg";
export const resources = {
  "userscript.js": _js,
  "images\\aww-cat.svg": _asset,
  "images\\cat.svg": _asset2,
  "images\\cool-cat.svg": _asset3,
  "images\\fav-it-cat.svg": _asset4,
  "images\\gobo.svg": _asset5,
  "images\\huh-cat.svg": _asset6,
  "images\\lol-cat.svg": _asset7,
  "images\\love-it-cat.svg": _asset8,
  "images\\meow.svg": _asset9,
  "images\\pizza-cat.svg": _asset10,
  "images\\rainbow-cat.svg": _asset11,
  "images\\tongue-out-cat.svg": _asset12,
  "images\\upside-down-cat.svg": _asset13,
  "images\\waffle.svg": _asset14,
  "images\\wink-cat.svg": _asset15,
};
