/* generated by pull.js */
const manifest = {
  "name": "Messages in editor",
  "description": "Displays your message count in the editor menu bar.",
  "credits": [
    {
      "name": "TheColaber"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "tags": [
    "recommended",
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
