/* generated by pull.js */
const manifest = {
  "name": "Name scripts before backpacking",
  "description": "Asks you to name scripts after you drag them into the backpack, instead of using the default name \"code\".",
  "credits": [
    {
      "name": "TheColaber"
    }
  ],
  "tags": [
    "new"
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true
};
export default manifest;
