/* generated by pull.js */
const manifest = {
  "name": "Instant forum read indicators",
  "description": "Automatically shows a topic as read when clicking on it on a forum category's page without requiring a reload.",
  "tags": [
    "new"
  ],
  "credits": [
    {
      "link": "https://scratch.mit.edu/mybearworld",
      "name": "mybearworld"
    }
  ],
  "userscripts": [],
  "userstyles": [],
  "dynamicDisable": true
};
export default manifest;
