/* generated by pull.js */
const manifest = {
  "name": "Horizontal My Stuff tabs",
  "description": "Moves the My Stuff navigation buttons (\"All Projects\", \"My Studios\", \"Trash\") to the top of the page, instead of keeping them on the left.",
  "tags": [
    "theme"
  ],
  "credits": [
    {
      "name": "Maximouse",
      "link": "https://scratch.mit.edu/users/Maximouse/"
    }
  ],
  "dynamicDisable": true,
  "userstyles": []
};
export default manifest;
