/* generated by pull.js */
const manifest = {
  "name": "Remaining reply counter",
  "description": "Shows you how many more replies can be posted on each comment thread in a studio before reaching the limit of 25.",
  "credits": [
    {
      "name": "BarelySmooth",
      "link": "https://scratch.mit.edu/users/BarelySmooth/"
    }
  ],
  "userscripts": [],
  "userstyles": [],
  "settings": [
    {
      "name": "Only show if less than 10 replies remain",
      "id": "show_only_if_less_than_10",
      "type": "boolean",
      "default": true
    }
  ],
  "tags": [
    "new"
  ],
  "dynamicDisable": true
};
export default manifest;
