/* generated by pull.js */
const manifest = {
  "name": "Point towards random direction block",
  "description": "Adds a \"random direction\" option to the \"point towards ()\" block that makes the sprite point in a random direction. This will work for everyone using the project.",
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "new"
  ],
  "enabledByDefault": false,
  "dynamicDisable": true,
  "credits": [
    {
      "name": "Tacodiva",
      "link": "https://scratch.mit.edu/users/Tacodiva7729/"
    },
    {
      "name": "pufferfish101007",
      "link": "https://scratch.mit.edu/users/pufferfish101007/"
    },
    {
      "name": "emir4169"
    }
  ]
};
export default manifest;
