/* generated by pull.js */
const manifest = {
  "name": "Unshare button in editor",
  "description": "Replaces the \"Shared\" button next to the project title box with a button to unshare the project.",
  "credits": [
    {
      "name": "Weredime (9gr)",
      "link": "https://scratch.mit.edu/users/9gr/"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "button.css"
    }
  ],
  "tags": [
    "new"
  ],
  "relatedAddons": [
    "share-through-mystuff"
  ]
};
export default manifest;
