/* generated by pull.js */
const manifest = {
  "name": "Additional project dates",
  "description": "Hover over a project's share date for information on when exactly it was created, shared and last edited.",
  "credits": [
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber/"
    },
    {
      "name": "Weredime (9gr)",
      "link": "https://scratch.mit.edu/users/9gr/"
    },
    {
      "name": "AeroKoder",
      "link": "https://scratch.mit.edu/users/AeroKoder/"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "new"
  ],
  "enabledByDefault": false
};
export default manifest;
