/* generated by pull.js */
const manifest = {
  "name": "Full areas",
  "description": "Shows the full content of areas with limited height, such as user signatures on the forums and What I've been doing on profiles, by making them resizable or scrollable.",
  "credits": [
    {
      "name": "GrahamSH"
    },
    {
      "name": "NitroCipher/ZenithRogue"
    },
    {
      "name": "TheColaber",
      "link": "https://scratch.mit.edu/users/TheColaber/"
    },
    {
      "name": "cobalt",
      "link": "https://github.com/cobaltt7"
    }
  ],
  "settings": [
    {
      "name": "What I've been doing",
      "id": "whatworkingon",
      "type": "boolean",
      "default": true
    },
    {
      "name": "What's Happening?",
      "id": "whathappen",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Project titles",
      "id": "titles",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Forum signatures",
      "id": "signature",
      "type": "boolean",
      "default": true
    },
    {
      "name": "Forum Scratchblocks",
      "id": "blocks",
      "type": "boolean",
      "default": true
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "resetScroll.js"
    }
  ],
  "userstyles": [
    {
      "url": "titles.css",
      "if": {
        "settings": {
          "titles": true
        }
      }
    }
  ],
  "tags": [
    "recommended",
    "new"
  ],
  "relatedAddons": [
    "infinite-scroll"
  ],
  "enabledByDefault": true
};
export default manifest;
