/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./sprites.css";
import _css2 from "!css-loader!./costumes.css";
import _css3 from "!css-loader!./sounds.css";
import _css4 from "!css-loader!./show-trash-shortcut.css";
export const resources = {
  "userscript.js": _js,
  "sprites.css": _css,
  "costumes.css": _css2,
  "sounds.css": _css3,
  "show-trash-shortcut.css": _css4,
};
